In [1]:
import pandas as pd
import numpy as np
import openpyxl

In [2]:
df = pd.read_excel("Nassau Candy Distributor.xlsx")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [3]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(10)
memory usage: 1.4+ MB

,Row ID,Order Date,Ship Date,Customer ID,Sales,Units,Gross Profit,Cost
count,10194.000000,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2025-03-13 03:08:26.415538176,2028-10-23 23:20:43.790465024,134468.961154,13.908537,3.791838,9.166451,4.742087
min,1.000000,2024-01-02 00:00:00,2026-06-30 00:00:00,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,2024-09-28 00:00:00,2027-11-09 00:00:00,117212.000000,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,2025-04-06 12:00:00,2028-12-18 00:00:00,133550.000000,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,2025-09-16 00:00:00,2029-11-08 00:00:00,152051.000000,18.000000,5.000000,12.250000,5.700000
max,10194.000000,2025-12-31 00:00:00,2030-06-28 00:00:00,192314.000000,260.000000,14.000000,130.000000,130.000000
std,2942.898656,NaN,NaN,20231.483007,11.341020,2.228317,6.643740,5.061647

In [4]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [5]:
df.dropna(subset=[
    "Order Date",
    "Ship Date",
    "State/Province",
    "Region",
    "Product Name",
    "Ship Mode"
], inplace=True)

In [26]:
df["Order Date"] = pd.to_datetime(df["Order Date"], dayfirst=True)
df["Ship Date"] = pd.to_datetime(df["Ship Date"], dayfirst=True)

In [27]:
df[["Order Date","Ship Date"]].head()

  Order Date  Ship Date
0 2024-01-03 2026-06-30
1 2024-01-04 2026-07-01
2 2024-01-04 2026-07-01
3 2024-01-04 2026-07-01
4 2024-01-05 2026-07-05

In [28]:
df.dropna(subset=["Order Date","Ship Date"], inplace=True)

In [29]:
df["Shipping Lead Time"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

In [30]:
df = df[df["Shipping Lead Time"] >= 0]
df = df[df["Shipping Lead Time"] <= 15]

In [31]:
df["Shipping Lead Time"].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Shipping Lead Time, dtype: float64

In [11]:
df = df[df["Shipping Lead Time"] >= 0]

In [12]:
df = df.drop_duplicates()

In [13]:
df.describe()

,Row ID,Order Date,Ship Date,Customer ID,Sales,Units,Gross Profit,Cost,Shipping Lead Time
count,10194.000000,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2025-03-13 03:08:26.415538176,2028-10-23 23:20:43.790465024,134468.961154,13.908537,3.791838,9.166451,4.742087,1320.841868
min,1.000000,2024-01-02 00:00:00,2026-06-30 00:00:00,100006.000000,1.250000,1.000000,0.250000,0.600000,904.000000
25%,2549.250000,2024-09-28 00:00:00,2027-11-09 00:00:00,117212.000000,7.200000,2.000000,4.900000,2.400000,1271.000000
50%,5097.500000,2025-04-06 12:00:00,2028-12-18 00:00:00,133550.000000,10.800000,3.000000,7.470000,3.600000,1274.000000
75%,7645.750000,2025-09-16 00:00:00,2029-11-08 00:00:00,152051.000000,18.000000,5.000000,12.250000,5.700000,1638.000000
max,10194.000000,2025-12-31 00:00:00,2030-06-28 00:00:00,192314.000000,260.000000,14.000000,130.000000,130.000000,1642.000000
std,2942.898656,NaN,NaN,20231.483007,11.341020,2.228317,6.643740,5.061647,262.444892

In [14]:
df = df[df["Sales"] >= 0]
df = df[df["Units"] > 0]
df = df[df["Cost"] >= 0]

In [15]:
df["Product Name"] = df["Product Name"].str.strip()

In [16]:
factory_map = {

"Wonka Bar - Nutty Crunch Surprise":"Lot's O' Nuts",
"Wonka Bar - Fudge Mallows":"Lot's O' Nuts",
"Wonka Bar -Scrumdiddlyumptious":"Lot's O' Nuts",

"Wonka Bar - Milk Chocolate":"Wicked Choccy's",
"Wonka Bar - Triple Dazzle Caramel":"Wicked Choccy's",

"Laffy Taffy":"Sugar Shack",
"SweeTARTS":"Sugar Shack",
"Nerds":"Sugar Shack",
"Fun Dip":"Sugar Shack",
"Fizzy Lifting Drinks":"Sugar Shack",

"Everlasting Gobstopper":"Secret Factory",
"Lickable Wallpaper":"Secret Factory",
"Wonka Gum":"Secret Factory",

"Hair Toffee":"The Other Factory",
"Kazookles":"The Other Factory"

}

In [17]:
df["Factory"] = df["Product Name"].map(factory_map)

In [18]:
df["Factory"].value_counts()

Factory
Lot's O' Nuts        5692
Wicked Choccy's      4152
Secret Factory        217
The Other Factory     100
Sugar Shack            33
Name: count, dtype: int64

In [19]:
df["Route"] = df["Factory"] + " → " + df["State/Province"]

In [20]:
df[["Factory","State/Province","Route"]].head()

           Factory State/Province                           Route
0  Wicked Choccy's          Texas         Wicked Choccy's → Texas
1  Wicked Choccy's       Illinois      Wicked Choccy's → Illinois
2    Lot's O' Nuts       Illinois        Lot's O' Nuts → Illinois
3    Lot's O' Nuts       Illinois        Lot's O' Nuts → Illinois
4  Wicked Choccy's   Pennsylvania  Wicked Choccy's → Pennsylvania

In [21]:
df["Ship Mode"].unique()

array(['Standard Class', 'First Class', 'Second Class', 'Same Day'],
      dtype=object)

In [22]:
df.shape

(10194, 21)

In [23]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time,Factory,Route
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909,Wicked Choccy's,Wicked Choccy's → Texas
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909,Wicked Choccy's,Wicked Choccy's → Illinois
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909,Lot's O' Nuts,Lot's O' Nuts → Illinois
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909,Lot's O' Nuts,Lot's O' Nuts → Illinois
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912,Wicked Choccy's,Wicked Choccy's → Pennsylvania

In [24]:
df.to_excel("cleaned_nassau_shipping_data.xlsx", index=False)

In [25]:
print("Total Shipments:", df["Order ID"].nunique())

print("Average Shipping Lead Time:", df["Shipping Lead Time"].mean())

print("Total Routes:", df["Route"].nunique())

print("Ship Modes:", df["Ship Mode"].unique())

Total Shipments: 8549
Average Shipping Lead Time: 1320.8418677653522
Total Routes: 196
Ship Modes: ['Standard Class' 'First Class' 'Second Class' 'Same Day']